---
- name: Check if PostgreSQL is installed
  shell: dpkg-query -l postgresql-9.3
  register: postgres_installed
  failed_when: postgres_installed.rc > 1

- name: Check if MariaDB is installed
  shell: dpkg-query -l mariadb-server
  register: mariadb_installed
  failed_when: mariadb_installed.rc > 1

- name: Check if MySQL is installed
  shell: dpkg-query -l mysql-server
  register: mysql_installed
  failed_when: mysql_installed.rc > 1
