---
# mariadb-server and mysql-server conflict with each other
- name: Uninstall MariaDB
  apt: name=mariadb-server state=absent
  ignore_errors: true

- name: Autoremove packages
  command: apt-get autoremove -y

- name: Install MySQL
  apt: name=mysql-server state=present
  notify:
  - Disable PostgreSQL service
  - Reload MySQL service
