---
# - name: Disable non-Apache httpd servers
#   notify:
#   - Disable httpd services

- name: Install Apache
  apt: name=apache2 state=present
  notify:
  - Disable Lighttpd service

- name: Add new Vagrant virtual host config
  template:
    src=vagrant.conf.j2
    dest=/etc/apache2/sites-available/vagrant.conf
  notify:
  - Reload Apache

- name: Remove the Apache default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
  - Reload Apache

- name: Enable our Vagrant Apache virtual host config
  file:
   src=/etc/apache2/sites-available/vagrant.conf
   dest=/etc/apache2/sites-enabled/vagrant.conf
   state=link
  notify:
  - Reload Apache
