---
- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-cli
    - php5-mysql
    - php5-intl
    - php5-curl
    - php5-xmlrpc
    - php5-gd
    - php5-json
    - php5-mcrypt
- name: Install CGI module
  apt: name=php5-cgi state=present
  when: httpd_server == 'lighttpd'
