---
- hosts: all
  sudo: true
  vars:
    # Valid values lighttpd|apache
    httpd_server: 'lighttpd'
    # Valid values: postgres|mariadb|mysql
    database_server: 'postgres'
  roles:
    - common
    - database
    - httpd
    - php
